language: node_js
node_js:
  - 4
services:
  - mongodb
addons:
  apt:
    sources:
    - mongodb-3.2.4-precise
    packages:
    - mongodb-org-server
    sources:
    - ubuntu-toolchain-r-test
    packages:
    - gcc-4.8
    - g++-4.8
env:
  - CXX=g++-4.8
sudo: required
install:
  - npm install -g eslint mocha chai
before_script: npm install
script:
  - npm run test
  - npm run lint
